export const EVENT = {
  name: "CLU REGISTRY DISCOURSE",
  fullTitle: "Governance, Innovation and Service: Changing Higher Education Management",
  type: "Chrisland University Maiden Registry Discourse",
  date: "Thursday, 15 October 2026",
  dateISO: "2026-10-15T09:00:00+01:00",
  venue: "University Auditorium, Chrisland University, Abeokuta",
  startTime: "9:00 a.m. WAT (Africa/Lagos, UTC+1)",
  participation: ["Physical", "Online via Zoom"] as const,
  phone: "+234 703 834 7947",
  phoneHref: "tel:+2347038347947",
  whatsappHref: "https://wa.me/2347038347947",
  whatsappPrefill: "Hello, I need assistance with the CLU Registry Discourse.",
  email: "registrydisourse@gmail.com",
  zoomTopic: "Governance, Innovation and Service: Changing Higher Education Management",
  zoomUrl: "https://us06web.zoom.us/j/84733111732?pwd=a5FHnBUprDgddIbP0bIAzzpBRnvWlx.1",
  zoomTime: "15 October 2026, 9:00 a.m. West Central Africa",
} as const;

export const BRAND = {
  purple: "#4C1769",
  purpleDark: "#3A1150",
  gold: "#C9B676",
  goldLight: "#E8D9A8",
  orange: "#B25900",
  green: "#0E7C3E",
} as const;

export const PEOPLE = [
  {
    slug: "bowo-olateru-olangbegi",
    name: "Prince Bowo Olateru-Olagbegi, BSc, FCA",
    role: "Chairman of the Day — Member, Governing Council, Chrisland University",
    badge: "Chairman",
    excerpt: "Public speaker, successful businessman, Fellow of the Institute of Chartered Accountants of Nigeria and graduate of the University of Lagos. Serves on the boards of several companies and is Chairman of Asherlogic Ltd, Bono Foods Ltd, Olbot Inc and COPAD.",
    bio: "Prince Bowo Olateru-Olagbegi, BSc, FCA is a public speaker and a successful businessman. He is a Fellow of the Institute of Chartered Accountants of Nigeria and a graduate of the University of Lagos, Nigeria. He serves on the boards of a range of companies including Cards Technology Ltd, CALM IT Global Ltd, Micfade (W.A) Ltd, Rolbotech Solutions Limited, TWPC Tech Ltd and many others. He has attended many conferences and participated in different leadership programs. He works with many organizations as a consultant, using his technical competencies and skills to meet the goals and objectives of the organizations. With years of experience as an information consultant, he successfully interacts with a diverse group of end users in different spheres, to navigate, train and advise on diverse matters. He has an outstanding track record of efficiency and effectiveness in managing communications and customer relationships. An independent thinker with proven AI and computer/information technology competency, strong communication skills and the ability to organize and plan successfully. He is accustomed to a fast-paced work environment, dealing with a variety of tasks and responsibilities in an efficient and accurate manner. He is Chairman of Asherlogic Ltd, an information technology company, as well as Bono Foods Ltd. He was a member of the Board of Coordinators of RCCGNA. He is Chairman of Olbot Inc, a healthcare services company based in the USA. He is the Chairman of COPAD, an NGO that promotes public accountability and development. He is a member of the Governing Council of Chrisland University, Nigeria. He has authored a number of books, including 'Corruption Talks', a conversation-style exposition on the ills of corruption, as well as 'Thought Transformers', among others.",
    initials: "BO",
    photo: "/people/bowo-olateru-olangbegi.png",
    flip: false,
  },
  {
    slug: "oyedunni-arulogun",
    name: "Professor Oyedunni Sola Arulogun FAAS, FSE, FRSPH, FAIPH",
    role: "Chief Host — Vice-Chancellor, Chrisland University, Abeokuta",
    badge: "Chief Host",
    excerpt: "Nigerian public health expert and academic, Vice-Chancellor of Chrisland University and Professor of Health Promotion and Education, trained at the University of Ibadan. Her work focuses on health promotion, reproductive health, community engagement, mentoring and capacity building.",
    bio: "Professor Oyedunni Sola Arulogun FAAS, FSE, FRSPH, FAIPH is a Nigerian public health expert and academic, currently serving as Vice-Chancellor of Chrisland University. She is a Professor of Health Promotion and Education, trained at the University of Ibadan, where she earned degrees in Special Education, Public Health, and a PhD. Her work focuses on health promotion, reproductive health, community engagement, mentoring and capacity building. She has held leadership roles including Dean of the Faculty of Public Health, Director, Centre for Entrepreneurship & Innovation, University Orator and member of the University of Ibadan Governing Council.",
    initials: "OA",
    photo: "/people/oyedunni-arulogun.png",
    flip: false,
  },
  {
    slug: "mojisola-ladipo",
    name: "Chief (Mrs.) Mojisola Olusola Ladipo, FNIM, mni",
    altName: "Dr. (Mrs.) Moji Ladipo",
    role: "Lecturer of the Day",
    badge: "Keynote Lecturer",
    excerpt: "Distinguished university administrator and the first female Registrar of the University of Ibadan. Served as Registrar for ten years and contributed extensively to professional university administration, leadership development, and mentoring in Nigeria.",
    bio: "Chief (Mrs.) Mojisola Olusola Ladipo, FNIM, mni, is a distinguished university administrator and the first female Registrar of the University of Ibadan. She served as Registrar for ten years and has contributed extensively to professional university administration, leadership development, training, and mentoring in Nigeria. She earned a first degree in English and a master's in Industrial and Labour Relations from the University of Ibadan and helped revive the Committee of Registrars of Nigerian Universities.",
    initials: "ML",
    photo: "/people/mojisola-ladipo.png",
    flip: true,
  },
  {
    slug: "sb-omotoso",
    name: "Mr. Samuel Babatola Omotoso, FCIA",
    role: "Host — Registrar, Chrisland University, Abeokuta",
    badge: "Host & Convener",
    excerpt: "Distinguished Fellow of the Chartered Institute of Administration (FCIA) and Registrar of Chrisland University, with over three decades of experience in university administration and general management. A Foundation Member of the Abeokuta Polo Club.",
    bio: "Mr. Samuel Babatola Omotoso, a distinguished Fellow of the Chartered Institute of Administration (FCIA), is the Registrar of Chrisland University, bringing over three decades of experience in university administration and general management. A seasoned professional administrator, he is committed to excellence and the achievement of organisational goals. He also champions the responsible and ethical use of artificial intelligence to promote innovation, efficiency and effective administration. His career reflects a steadfast commitment to institutional growth, integrity and sound governance. Combining extensive experience with a passion for innovation, he embodies purposeful leadership and a dedication to building a stronger future for the university community. He is a Foundation Member of the Abeokuta Polo Club.",
    initials: "SO",
    photo: "/people/sb-omotoso.png",
    flip: false,
  },
] as const;

export const PROGRAMME = [
  { time: "08:00 – 08:45", title: "Arrival & Registration", speaker: "LOC Secretariat", venue: "Auditorium Foyer", desc: "Collection of access passes, kit and seating." },
  { time: "09:00 – 09:20", title: "Opening & National Anthem", speaker: "University Anthem / Protocol", venue: "Main Auditorium", desc: "Welcome, introductions and opening prayers." },
  { time: "09:20 – 09:35", title: "Welcome Address", speaker: "Mr. S. B. Omotoso — Registrar", venue: "Main Auditorium", desc: "Host remarks and discourse framing." },
  { time: "09:35 – 09:50", title: "Chief Host Address", speaker: "Prof. Oyedunni Sola Arulogun — Vice-Chancellor", venue: "Main Auditorium", desc: "Vision for governance and service." },
  { time: "09:50 – 10:05", title: "Chairman's Opening Remarks", speaker: "Prince Bowo Olateru-Olagbegi — Governing Council Member", venue: "Main Auditorium", desc: "Contextualising change in higher education management." },
  { time: "10:05 – 11:00", title: "Keynote: Governance, Innovation & Service", speaker: "Chief (Mrs.) Mojisola Ladipo, FNIM, mni", venue: "Main Auditorium + Zoom", desc: "The lecture of the day — changing higher education management." },
  { time: "11:00 – 11:30", title: "Tea Break & Networking", speaker: "—", venue: "Auditorium Lounge", desc: "Refreshments and gallery." },
  { time: "11:30 – 12:30", title: "Panel Discourse & Q&A", speaker: "Panel of Registrars & Administrators", venue: "Main Auditorium + Zoom", desc: "Innovation in registry practice, digital governance, service excellence." },
  { time: "12:30 – 12:45", title: "Vote of Thanks & Closing", speaker: "LOC Chairman", venue: "Main Auditorium", desc: "Appreciation and next steps." },
  { time: "12:45 – 13:30", title: "Group Photographs & Departure", speaker: "—", venue: "Auditorium Forecourt", desc: "Certificates and materials released to verified attendees." },
] as const;

export const STATS = [
  { label: "Participants expected", value: "500+", sub: "Physical & Online" },
  { label: "Institutions", value: "40+", sub: "Universities & Polytechnics" },
  { label: "Years of registry wisdom", value: "30+", sub: "Keynote experience" },
  { label: "Discourse edition", value: "Maiden", sub: "Historic first" },
];
