export const EVENT = {
  name: "CLU REGISTRY DISCOURSE",
  fullTitle: "Governance, Innovation and Service: Changing Higher Education Management",
  type: "Chrisland University Maiden Registry Discourse",
  date: "Thursday, 15 October 2026",
  dateISO: "2026-10-15T09:00:00+01:00",
  venue: "University Auditorium, Chrisland University, Abeokuta",
  startTime: "9:00 a.m. WAT (Africa/Lagos, UTC+1)",
  participation: ["Physical", "Online via Zoom"] as const,
  phone: "+234 703 834 7947",
  phoneHref: "tel:+2347038347947",
  whatsappHref: "https://wa.me/2347038347947",
  whatsappPrefill: "Hello, I need assistance with the CLU Registry Discourse.",
  email: "registrydisourse@gmail.com",
  zoomTopic: "Governance, Innovation and Service: Changing Higher Education Management",
  zoomUrl: "https://us06web.zoom.us/j/84733111732?pwd=a5FHnBUprDgddIbP0bIAzzpBRnvWlx.1",
  zoomTime: "15 October 2026, 9:00 a.m. West Central Africa",
} as const;

export const BRAND = {
  purple: "#4C1769",
  purpleDark: "#3A1150",
  gold: "#C9B676",
  goldLight: "#E8D9A8",
  orange: "#B25900",
  green: "#0E7C3E",
} as const;

export const PEOPLE = [
  {
    slug: "bowo-olateru-olangbegi",
    name: "Prince Bowo Olateru-Olagbegi, BSc, FCA",
    role: "Chairman of the Day — Member, Governing Council, Chrisland University",
    badge: "Chairman",
    excerpt: "Public speaker, successful businessman, Fellow of the Institute of Chartered Accountants of Nigeria and graduate of the University of Lagos. Serves on the boards of several companies and is Chairman of Asherlogic Ltd, Bono Foods Ltd, Olbot Inc and COPAD.",
    bio: "Prince Bowo Olateru-Olagbegi, BSc, FCA is a public speaker, successful businessman, Fellow of the Institute of Chartered Accountants of Nigeria and graduate of the University of Lagos. He serves on the boards of several companies, including Cards Technology Ltd and TWPC Tech Ltd, and works with many organisations as an information technology consultant. He is Chairman of Asherlogic Ltd, Bono Foods Ltd, Olbot Inc, a healthcare services company based in the USA, and COPAD, an NGO that promotes public accountability and development. He is a member of the Governing Council of Chrisland University and has authored books including 'Corruption Talks' and 'Thought Transformers'.",
    initials: "BO",
    photo: "/people/bowo-olateru-olangbegi.png",
    flip: false,
  },
  {
    slug: "oyedunni-arulogun",
    name: "Professor Oyedunni Sola Arulogun FAAS, FSE, FRSPH, FAIPH",
    role: "Chief Host — Vice-Chancellor, Chrisland University, Abeokuta",
    badge: "Chief Host",
    excerpt: "Nigerian public health expert and academic, Vice-Chancellor of Chrisland University and Professor of Health Promotion and Education, trained at the University of Ibadan. Her work focuses on health promotion, reproductive health, community engagement, mentoring and capacity building.",
    bio: "Professor Oyedunni Sola Arulogun FAAS, FSE, FRSPH, FAIPH is a Nigerian public health expert and academic, currently serving as Vice-Chancellor of Chrisland University. She is a Professor of Health Promotion and Education, trained at the University of Ibadan, where she earned degrees in Special Education, Public Health, and a PhD. Her work focuses on health promotion, reproductive health, community engagement, mentoring and capacity building. She has held leadership roles including Dean of the Faculty of Public Health, Director, Centre for Entrepreneurship & Innovation, University Orator and member of the University of Ibadan Governing Council.",
    initials: "OA",
    photo: "/people/oyedunni-arulogun.png",
    flip: false,
  },
  {
    slug: "mojisola-ladipo",
    name: "Chief (Mrs.) Mojisola Olusola Ladipo, FNIM, mni",
    altName: "Dr. (Mrs.) Moji Ladipo",
    role: "Lecturer of the Day",
    badge: "Keynote Lecturer",
    excerpt: "Distinguished university administrator and the first female Registrar of the University of Ibadan. Served as Registrar for ten years and contributed extensively to professional university administration, leadership development, and mentoring in Nigeria.",
    bio: "Chief (Mrs.) Mojisola Olusola Ladipo, FNIM, mni, is a distinguished university administrator and the first female Registrar of the University of Ibadan. She served as Registrar for ten years and has contributed extensively to professional university administration, leadership development, training, and mentoring in Nigeria. She earned a first degree in English and a master's in Industrial and Labour Relations from the University of Ibadan and helped revive the Committee of Registrars of Nigerian Universities.",
    initials: "ML",
    photo: "/people/mojisola-ladipo.png",
    flip: true,
  },
  {
    slug: "sb-omotoso",
    name: "Mr. Samuel Babatola Omotoso, FCIA",
    role: "Host — Registrar, Chrisland University, Abeokuta",
    badge: "Host & Convener",
    excerpt: "Distinguished Fellow of the Chartered Institute of Administration (FCIA) and Registrar of Chrisland University, with over three decades of experience in university administration and general management. A Foundation Member of the Abeokuta Polo Club.",
    bio: "Mr. Samuel Babatola Omotoso, a distinguished Fellow of the Chartered Institute of Administration (FCIA), is the Registrar of Chrisland University, bringing over three decades of experience in university administration and general management. He is committed to excellence and the achievement of organisational goals, and champions the responsible and ethical use of artificial intelligence to promote innovation, efficiency and effective administration. His career reflects a steadfast commitment to institutional growth, integrity and sound governance. He is a Foundation Member of the Abeokuta Polo Club.",
    initials: "SO",
    photo: "/people/sb-omotoso.png",
    flip: false,
  },
] as const;

export const PROGRAMME = [
  { time: "08:00 – 08:45", title: "Arrival & Registration", speaker: "LOC Secretariat", venue: "Auditorium Foyer", desc: "" },
  { time: "09:00 – 09:20", title: "Opening & National Anthem", speaker: "University Anthem / Protocol", venue: "Main Auditorium", desc: "" },
  { time: "09:20 – 09:30", title: "Recognition", speaker: "Protocol", venue: "Main Auditorium", desc: "Introduction of dignitaries." },
  { time: "09:30 – 09:40", title: "Welcome Address", speaker: "Mr. S. B. Omotoso — Registrar", venue: "Main Auditorium", desc: "" },
  { time: "09:40 – 09:50", title: "Chief Host Address", speaker: "Prof. Oyedunni Sola Arulogun — Vice-Chancellor", venue: "Main Auditorium", desc: "" },
  { time: "09:50 – 10:00", title: "Chairman's Opening Remarks", speaker: "Prince Bowo Olateru-Olagbegi — Governing Council Member", venue: "Main Auditorium", desc: "" },
  { time: "10:00 – 10:05", title: "Citation of the Keynote Lecturer", speaker: "Protocol", venue: "Main Auditorium", desc: "" },
  { time: "10:05 – 11:00", title: "Keynote Lecture", speaker: "Chief (Mrs.) Mojisola Ladipo, FNIM, mni", venue: "Main Auditorium + Zoom", desc: "" },
  { time: "11:00 – 11:30", title: "Tea Break & Networking", speaker: "—", venue: "Auditorium Lounge", desc: "" },
  { time: "12:30 – 12:45", title: "Vote of Thanks & Closing", speaker: "LOC Chairman", venue: "Main Auditorium", desc: "" },
  { time: "12:45 – 13:30", title: "Group Photographs & Departure", speaker: "—", venue: "Auditorium Forecourt", desc: "" },
] as const;

export const STATS = [
  { label: "Participants expected", value: "500+", sub: "Physical & Online" },
  { label: "Institutions", value: "40+", sub: "Universities & Polytechnics" },
  { label: "Years of registry wisdom", value: "30+", sub: "Keynote experience" },
  { label: "Discourse edition", value: "Maiden", sub: "Historic first" },
];
